# Generated by Django 3.1.1 on 2021-01-11 18:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("founders", "0002_auto_20210107_2040"),
    ]

    operations = [
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mentor_feedback", models.TextField()),
                ("coach_feedback", models.TextField()),
                (
                    "goals",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=500), size=None
                        ),
                        size=None,
                    ),
                ),
                (
                    "action_helped",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=500), size=None
                        ),
                        size=None,
                    ),
                ),
                ("learning_conversation", models.TextField()),
                ("unplanned_action_help", models.TextField()),
                (
                    "founder_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Progress",
                        to="founders.founder",
                    ),
                ),
            ],
        ),
    ]
