# Generated by Django 3.1.1 on 2021-01-11 19:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("founders", "0003_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="action_helped",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500), size=None
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="goals",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500), size=None
            ),
        ),
    ]
