# Generated by Django 3.1.1 on 2021-01-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("founders", "0005_auto_20210111_1937"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="slug",
            field=models.SlugField(
                blank=True, default="112321", max_length=250, null=True
            ),
        ),
    ]
