# Generated by Django 3.1.1 on 2021-01-14 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("founders", "0007_auto_20210112_1423"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="end_date",
            field=models.CharField(default=datetime.date(2021, 1, 8), max_length=255),
        ),
        migrations.AddField(
            model_name="progress",
            name="start_date",
            field=models.CharField(default=datetime.date(2021, 1, 11), max_length=255),
        ),
    ]
