# Generated by Django 3.1.1 on 2021-01-14 19:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("founders", "0010_auto_20210114_1845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="coach_feedback",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="progress",
            name="goals",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500), null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="learning_conversation",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="progress",
            name="mentor_feedback",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="progress",
            name="unplanned_action_help",
            field=models.TextField(null=True),
        ),
    ]
