# Generated by Django 3.1.1 on 2021-01-14 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("founders", "0011_auto_20210114_1921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="founder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="founder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
