# Generated by Django 3.1.1 on 2021-01-19 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("founders", "0013_auto_20210114_1923"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="end_date",
            field=models.CharField(default=datetime.date(2021, 1, 24), max_length=255),
        ),
        migrations.AlterField(
            model_name="progress",
            name="start_date",
            field=models.CharField(default=datetime.date(2021, 1, 18), max_length=255),
        ),
    ]
