# Generated by Django 3.1.1 on 2021-01-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("founders", "0014_auto_20210119_2033"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="lastweek_metric",
            field=models.IntegerField(default=12, null=True),
        ),
        migrations.AddField(
            model_name="progress",
            name="learning_stakeholder",
            field=models.TextField(default="Hi", null=True),
        ),
        migrations.AddField(
            model_name="progress",
            name="numberof_stakeholder",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="progress",
            name="target_market",
            field=models.CharField(default="hi", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="progress",
            name="top_priorities",
            field=models.TextField(default="hi", null=True),
        ),
    ]
