# Generated by Django 3.1.1 on 2021-01-26 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('founders', '0016_auto_20210126_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founder', to=settings.AUTH_USER_MODEL),
        ),
    ]
