# Generated by Django 3.1.1 on 2021-01-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startup_name", models.CharField(max_length=150)),
                ("website", models.CharField(max_length=100, unique=True)),
                ("about", models.TextField(max_length=300)),
                ("is_launched", models.BooleanField(default=False)),
                ("app_link", models.CharField(max_length=200)),
                ("video_link", models.CharField(max_length=100)),
            ],
        ),
    ]
