# Generated by Django 3.1.1 on 2021-01-06 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydetails",
            name="founder",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="startup_founder",
                to="users.customers",
            ),
            preserve_default=False,
        ),
    ]
