# Generated by Django 3.1.1 on 2021-01-07 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0002_companydetails_founder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companydetails",
            name="founder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ceo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
