# Generated by Django 3.1.1 on 2021-01-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_auto_20210107_0618"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companydetails",
            old_name="founder",
            new_name="customer",
        ),
    ]
