# Generated by Django 3.1.1 on 2021-01-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_auto_20210111_1331"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_link",
            field=models.CharField(
                default="""https://global-uploads.webflow.com/
                           5f4b9ee5f40a6467ebb252ce/5fd1fd23349ab9cc8612d7be_
                           Customers_resource%20library.png""",
                max_length=255,
            ),
        ),
    ]
