# Generated by Django 3.1.1 on 2021-01-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_post_image_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydetails",
            name="time_commitment",
            field=models.CharField(
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part Time"),
                    ("20", "20"),
                ],
                default="Part Time",
                max_length=100,
            ),
        ),
    ]
