# Generated by Django 3.1.1 on 2021-01-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_companydetails_time_commitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_link',
            field=models.CharField(default='https://global-uploads.webflow.com/\n                   5f4b9ee5f40a6467ebb252ce/5fd1fd23349ab9cc8\n                   612d7be_Customers_resource%20library.png', max_length=255),
        ),
    ]
